name: marc calvary
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4b0a06'
    - '#7f5614'
    - '#c4c7de'
    - '#af9390'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
