name: marc calvary
favicon: null
layout_spectrum: 0.7929993765428662
typography_spectrum: 0.5482817813754082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.919776314869523
  lightness: 0.09706069761887193
  saturation: 0.5761676346883178
  rhythmicContrast: 0.13690366107039154
purpose: []
