name: marc calvary
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5482817813754082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4b0a06'
    - '#7f5614'
    - '#c4c7de'
    - '#af9390'
  brandStrength: 1
  lightness: 0.09706069761887193
  saturation: 0.5
  rhythmicContrast: 0.13690366107039154
purpose: []
